### Variables
@apiurl = http://localhost:3001

### Admin login
POST {{apiurl}}/login
Content-Type: application/json

{
    "email": "matiasdario75@gmail.com",
    "password": "Vj-MVuj&*mti&k"
}

### User Login
POST {{apiurl}}/login
Content-Type: application/json

{
    "email": "adelta893@gmail.com",
    "password": "Auj@76vj7-b76"
}

### Refresh
GET {{apiurl}}/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDc0ODIwMjgsImlkIjoiYzRkMTc1ODMtYmQxMy00YjExLWIyMTQtMjZlYzFhMzMxNzdlIiwicm9sZXMiOlsidXNlciJdLCJ0b2tlbl90eXBlIjoicmVmcmVzaF90b2tlbiJ9.r8b71Q4yWCrWsx85fIHe9NvTE_Ci1HDFIkz53ZlxPYA

{}

### Validate Email
POST {{apiurl}}/validate-email
Content-Type: application/json

{
    "verification_code": "251044"
}

### Create User
POST {{apiurl}}/user
Content-Type: application/json

{
    "name": "Dário Matias Sales",
    "age": 18,
    "email": "adelta893@gmail.com",
    "password": "Auj@76vj7-b76B"
}

### Get User
GET {{apiurl}}/user/c4d17583-bd13-4b11-b214-26ec1a33177e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY5NjM1MzAsImlkIjoiYzRkMTc1ODMtYmQxMy00YjExLWIyMTQtMjZlYzFhMzMxNzdlIiwicm9sZXMiOlsidXNlciJdLCJ0b2tlbl90eXBlIjoiYWNjZXNzX3Rva2VuIn0.ZGAh9GZbAl6cJhwre0uzy5r2I622oXQakChoiaQ-q6g

{}

### Get Users
GET {{apiurl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY5NjI5ODUsImlkIjoiZTAxMzEwZWYtMTNmNy00N2VhLThkMDAtNTQ4YzIyODg5ZDE0Iiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiJ9.V4Tp1acqwqC39kf9Y2M1leo8MLfHda6Wkwkt_oYI8V8

{}

### Update User
PATCH {{apiurl}}/user/52dcbdac-e0f5-41d6-999c-d0cf8a0d80cb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY4Nzk3NTIsImlkIjoiZjM4N2I0YzYtMWMxNi00ZmE2LWE1MGYtM2E2ZTJjODI1YWM1Iiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiJ9.0cYFqmqoz7TXZtwXCKKw1lHCd4ZE5l9Bf6DIWH4XUIA

{
    "age": 20
}

### Delete User
DELETE {{apiurl}}/user/f387b4c6-1c16-4fa6-a50f-3a6e2c825ac5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY5NTc0ODcsImlkIjoiZjM4N2I0YzYtMWMxNi00ZmE2LWE1MGYtM2E2ZTJjODI1YWM1Iiwicm9sZXMiOlsiYWRtaW4iXSwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiJ9.nknFsBmVngD8EJM8df2AjAslM5mQEzxQdvnM2ZeR8Dw

{}
