### Variables
@apiurl = http://localhost:3001

### Create User
POST {{apiurl}}/user
Content-Type: application/json

{
    "name": "Dário",
    "age": 18,
    "email": "matiasdario75@gmail.com",
    "password": "1234567890"
}

### Get User
GET {{apiurl}}/user/52dcbdac-e0f5-41d6-999c-d0cf8a0d80cb
Content-Type: application/json

{}

### Get Users
GET {{apiurl}}/users
Content-Type: application/json

{}

### Update User
PATCH {{apiurl}}/user/52dcbdac-e0f5-41d6-999c-d0cf8a0d80cb
Content-Type: application/json

{
    "age": 50
}

### Delete User
DELETE {{apiurl}}/user/9f03db06-ea0b-4d92-b4f0-8b21ebf3d7f4
Content-Type: application/json

{}
