// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Tokens struct {
	UserID       uuid.UUID `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Users struct {
	ID         uuid.UUID    `json:"id"`
	Name       string       `json:"name"`
	Age        int32        `json:"age"`
	Email      string       `json:"email"`
	ValidEmail sql.NullBool `json:"valid_email"`
	Password   string       `json:"password"`
	Roles      []string     `json:"roles"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}
