// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailValidations struct {
	UserID           uuid.UUID `json:"user_id"`
	VerificationCode string    `json:"verification_code"`
	ExpirationTime   int32     `json:"expiration_time"`
	CreatedAt        time.Time `json:"created_at"`
}

type Tokens struct {
	UserID       uuid.UUID `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Users struct {
	ID            uuid.UUID    `json:"id"`
	Name          string       `json:"name"`
	Age           int32        `json:"age"`
	Email         string       `json:"email"`
	ValidEmail    sql.NullBool `json:"valid_email"`
	Password      string       `json:"password"`
	Roles         []string     `json:"roles"`
	LoginAttempts int32        `json:"login_attempts"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}
